select year as ano_premiacao,
       category as categoria,
       prize as premio,
       case when motivation = 'NA' then 'Não informado' else motivation end as motivo,
       prize_share as compartilhamento,
       laureate_id as id_laureado,
       laureate_type as tipo_laureado,
       full_name as nome_laureado,
        birth_date as data_nascimento,
        birth_city as cidade_nascimento,
        birth_country as pais_nascimento,
        sex as sexo,
        organization_name as nome_organizacao,
        organization_city as cidade_organizacao,
        organization_country as pais_organizacao,
        death_date as data_morte,
        death_city as cidade_morte,
        death_country as pais_morte
from {{ source('bronze', 'nobel') }}