version: 2

sources:
  - name: bronze
    tables:
      - name: netflix_titles
      - name: 9dias
      - name: nobel
      - name: social_media
      - name: pokemons
      - name: questoes_rows
      - name: questoes_gemini_rows
      - name: 2022_Billionaire_List
      - name: 2024_Billionaire_List
      - name: population_demographics
      - name: washington_crimes_march_2025
      - name: healthcare_dataset
      - name: cv_experience
      - name: cv_skill
      - name: cv_experience_skill
      - name: space_missions
      - name: ddna_event
      - name: ddna_product
      - name: ddna_customer