version: 2

sources:
  - name: src
    tables:
      - name: netflix_titles
      - name: 9dias
      - name: nobel
      - name: social_media
      - name: pokemons
      - name: questoes_rows
      - name: questoes_gemini_rows